set_location_assignment PIN_M8 -to row_o[0]
set_location_assignment PIN_L7 -to row_o[1]
set_location_assignment PIN_P9 -to row_o[2]
set_location_assignment PIN_N9 -to row_o[3]
set_location_assignment PIN_M9 -to row_o[4]
set_location_assignment PIN_M10 -to row_o[5]
set_location_assignment PIN_P11 -to row_o[6]
set_location_assignment PIN_N11 -to row_o[7]
set_location_assignment PIN_N6 -to column_o[0]
set_location_assignment PIN_P6 -to column_o[1]
set_location_assignment PIN_M6 -to column_o[2]
set_location_assignment PIN_M7 -to column_o[3]
set_location_assignment PIN_P8 -to column_o[4]
set_location_assignment PIN_N8 -to column_o[5]
set_location_assignment PIN_R9 -to CLK
set_location_assignment PIN_M1 -to RSTn
set_location_assignment PIN_E7 -to ps2_data_i
set_location_assignment PIN_D8 -to ps2_clk_i
set_location_assignment PIN_J1 -to led_o1
set_location_assignment PIN_J2 -to led_o2
set_location_assignment PIN_K1 -to led_o3
set_location_assignment	PIN_E6	-to Green_Sig
set_location_assignment	PIN_D5	-to Blue_Sig
set_location_assignment	PIN_C6	-to Red_Sig
set_location_assignment	PIN_D3	-to HSYNC_Sig
set_location_assignment	PIN_C3	-to VSYNC_Sig

set_location_assignment	PIN_A10	-to sdram_data[0]
set_location_assignment	PIN_B10	-to sdram_data[1]
set_location_assignment	PIN_A11 -to sdram_data[2]
set_location_assignment	PIN_B11	-to sdram_data[3]
set_location_assignment	PIN_A12	-to sdram_data[4]
set_location_assignment	PIN_B12	-to sdram_data[5]
set_location_assignment	PIN_A13	-to sdram_data[6]
set_location_assignment	PIN_B13	-to sdram_data[7]
set_location_assignment	PIN_A2	-to sdram_data[8]
set_location_assignment	PIN_B1 	-to sdram_data[9]
set_location_assignment	PIN_C2	-to sdram_data[10]
set_location_assignment	PIN_D1	-to sdram_data[11]
set_location_assignment	PIN_F2	-to sdram_data[12]
set_location_assignment	PIN_F1	-to sdram_data[13]
set_location_assignment	PIN_G2	-to sdram_data[14]
set_location_assignment	PIN_G1	-to sdram_data[15]
										
set_location_assignment	PIN_F15	-to sdram_addr[0]
set_location_assignment	PIN_F16	-to sdram_addr[1]
set_location_assignment	PIN_G15	-to sdram_addr[2]
set_location_assignment	PIN_G16	-to sdram_addr[3]
set_location_assignment	PIN_C8	-to sdram_addr[4]
set_location_assignment	PIN_A7	-to sdram_addr[5]
set_location_assignment	PIN_B7	-to sdram_addr[6]
set_location_assignment	PIN_A6	-to sdram_addr[7]
set_location_assignment	PIN_B6	-to sdram_addr[8]
set_location_assignment	PIN_A5	-to sdram_addr[9]
set_location_assignment	PIN_D16	-to sdram_addr[10]
set_location_assignment	PIN_B5	-to sdram_addr[11]
set_location_assignment	PIN_A4	-to sdram_addr[12]

set_location_assignment	PIN_A3	-to sdram_clk
set_location_assignment	PIN_C16	-to sdram_ba[0]
set_location_assignment	PIN_D15	-to sdram_ba[1]
set_location_assignment	PIN_A15	-to sdram_ncas
set_location_assignment	PIN_B4	-to sdram_clke
set_location_assignment	PIN_B16	-to sdram_nras
set_location_assignment	PIN_B14	-to sdram_nwe
set_location_assignment	PIN_C15	-to sdram_ncs
set_location_assignment	PIN_B3	-to sdram_dqm[1]
set_location_assignment	PIN_A14	-to sdram_dqm[0]